// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Player.proto

/*
Package Player is a generated protocol buffer package.

It is generated from these files:
	Player.proto

It has these top-level messages:
	CPlayerConnect
	CPlayerCreator
	CUiMessage
	CGameRaceStart
	CPlayerObjInfo
	CPlayerInfo
	CPlayerItem
	CPlayerTrun
	CPlayerState
	CPlayerGridChange
	C2SClientGameWorldOK
*/
package Player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CPlayerConnect struct {
	Clinetid         *uint32 `protobuf:"varint,1,req,name=Clinetid" json:"Clinetid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerConnect) Reset()                    { *m = CPlayerConnect{} }
func (m *CPlayerConnect) String() string            { return proto.CompactTextString(m) }
func (*CPlayerConnect) ProtoMessage()               {}
func (*CPlayerConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CPlayerConnect) GetClinetid() uint32 {
	if m != nil && m.Clinetid != nil {
		return *m.Clinetid
	}
	return 0
}

type CPlayerCreator struct {
	ClientId         *uint32 `protobuf:"varint,1,req,name=ClientId" json:"ClientId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerCreator) Reset()                    { *m = CPlayerCreator{} }
func (m *CPlayerCreator) String() string            { return proto.CompactTextString(m) }
func (*CPlayerCreator) ProtoMessage()               {}
func (*CPlayerCreator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CPlayerCreator) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

type CUiMessage struct {
	UiMsgName        *string  `protobuf:"bytes,1,req,name=UiMsgName" json:"UiMsgName,omitempty"`
	AkMsgParame      []uint32 `protobuf:"varint,2,rep,name=akMsgParame" json:"akMsgParame,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CUiMessage) Reset()                    { *m = CUiMessage{} }
func (m *CUiMessage) String() string            { return proto.CompactTextString(m) }
func (*CUiMessage) ProtoMessage()               {}
func (*CUiMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CUiMessage) GetUiMsgName() string {
	if m != nil && m.UiMsgName != nil {
		return *m.UiMsgName
	}
	return ""
}

func (m *CUiMessage) GetAkMsgParame() []uint32 {
	if m != nil {
		return m.AkMsgParame
	}
	return nil
}

type CGameRaceStart struct {
	ClientId         *uint32 `protobuf:"varint,1,req,name=ClientId" json:"ClientId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGameRaceStart) Reset()                    { *m = CGameRaceStart{} }
func (m *CGameRaceStart) String() string            { return proto.CompactTextString(m) }
func (*CGameRaceStart) ProtoMessage()               {}
func (*CGameRaceStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CGameRaceStart) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

type CPlayerObjInfo struct {
	X                *uint32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *uint32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	IHp              *uint32 `protobuf:"varint,3,req,name=iHp" json:"iHp,omitempty"`
	IMaxHp           *uint32 `protobuf:"varint,4,req,name=iMaxHp" json:"iMaxHp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerObjInfo) Reset()                    { *m = CPlayerObjInfo{} }
func (m *CPlayerObjInfo) String() string            { return proto.CompactTextString(m) }
func (*CPlayerObjInfo) ProtoMessage()               {}
func (*CPlayerObjInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CPlayerObjInfo) GetX() uint32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CPlayerObjInfo) GetY() uint32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *CPlayerObjInfo) GetIHp() uint32 {
	if m != nil && m.IHp != nil {
		return *m.IHp
	}
	return 0
}

func (m *CPlayerObjInfo) GetIMaxHp() uint32 {
	if m != nil && m.IMaxHp != nil {
		return *m.IMaxHp
	}
	return 0
}

type CPlayerInfo struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	EnterTime        *uint64 `protobuf:"varint,3,req,name=enterTime" json:"enterTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerInfo) Reset()                    { *m = CPlayerInfo{} }
func (m *CPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*CPlayerInfo) ProtoMessage()               {}
func (*CPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CPlayerInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CPlayerInfo) GetEnterTime() uint64 {
	if m != nil && m.EnterTime != nil {
		return *m.EnterTime
	}
	return 0
}

type CPlayerItem struct {
	Itemid           *uint32 `protobuf:"varint,1,req,name=itemid" json:"itemid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerItem) Reset()                    { *m = CPlayerItem{} }
func (m *CPlayerItem) String() string            { return proto.CompactTextString(m) }
func (*CPlayerItem) ProtoMessage()               {}
func (*CPlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CPlayerItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

type CPlayerTrun struct {
	ObjLogicID       *uint32 `protobuf:"varint,1,req,name=objLogicID" json:"objLogicID,omitempty"`
	FDir             *string `protobuf:"bytes,2,req,name=fDir" json:"fDir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerTrun) Reset()                    { *m = CPlayerTrun{} }
func (m *CPlayerTrun) String() string            { return proto.CompactTextString(m) }
func (*CPlayerTrun) ProtoMessage()               {}
func (*CPlayerTrun) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CPlayerTrun) GetObjLogicID() uint32 {
	if m != nil && m.ObjLogicID != nil {
		return *m.ObjLogicID
	}
	return 0
}

func (m *CPlayerTrun) GetFDir() string {
	if m != nil && m.FDir != nil {
		return *m.FDir
	}
	return ""
}

type CPlayerState struct {
	ObjLogicID       *uint32 `protobuf:"varint,1,req,name=objLogicID" json:"objLogicID,omitempty"`
	ObjState         *uint32 `protobuf:"varint,2,req,name=objState" json:"objState,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerState) Reset()                    { *m = CPlayerState{} }
func (m *CPlayerState) String() string            { return proto.CompactTextString(m) }
func (*CPlayerState) ProtoMessage()               {}
func (*CPlayerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CPlayerState) GetObjLogicID() uint32 {
	if m != nil && m.ObjLogicID != nil {
		return *m.ObjLogicID
	}
	return 0
}

func (m *CPlayerState) GetObjState() uint32 {
	if m != nil && m.ObjState != nil {
		return *m.ObjState
	}
	return 0
}

type CPlayerGridChange struct {
	ObjLogicID       *uint32 `protobuf:"varint,1,req,name=objLogicID" json:"objLogicID,omitempty"`
	X                *uint32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *uint32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerGridChange) Reset()                    { *m = CPlayerGridChange{} }
func (m *CPlayerGridChange) String() string            { return proto.CompactTextString(m) }
func (*CPlayerGridChange) ProtoMessage()               {}
func (*CPlayerGridChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CPlayerGridChange) GetObjLogicID() uint32 {
	if m != nil && m.ObjLogicID != nil {
		return *m.ObjLogicID
	}
	return 0
}

func (m *CPlayerGridChange) GetX() uint32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CPlayerGridChange) GetY() uint32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type C2SClientGameWorldOK struct {
	MyClientID       *uint32 `protobuf:"varint,1,req,name=myClientID" json:"myClientID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SClientGameWorldOK) Reset()                    { *m = C2SClientGameWorldOK{} }
func (m *C2SClientGameWorldOK) String() string            { return proto.CompactTextString(m) }
func (*C2SClientGameWorldOK) ProtoMessage()               {}
func (*C2SClientGameWorldOK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *C2SClientGameWorldOK) GetMyClientID() uint32 {
	if m != nil && m.MyClientID != nil {
		return *m.MyClientID
	}
	return 0
}

func init() {
	proto.RegisterType((*CPlayerConnect)(nil), "Player.cPlayerConnect")
	proto.RegisterType((*CPlayerCreator)(nil), "Player.cPlayerCreator")
	proto.RegisterType((*CUiMessage)(nil), "Player.cUiMessage")
	proto.RegisterType((*CGameRaceStart)(nil), "Player.cGameRaceStart")
	proto.RegisterType((*CPlayerObjInfo)(nil), "Player.cPlayerObjInfo")
	proto.RegisterType((*CPlayerInfo)(nil), "Player.cPlayerInfo")
	proto.RegisterType((*CPlayerItem)(nil), "Player.cPlayerItem")
	proto.RegisterType((*CPlayerTrun)(nil), "Player.cPlayerTrun")
	proto.RegisterType((*CPlayerState)(nil), "Player.cPlayerState")
	proto.RegisterType((*CPlayerGridChange)(nil), "Player.cPlayerGridChange")
	proto.RegisterType((*C2SClientGameWorldOK)(nil), "Player.c2sClientGameWorldOK")
}

func init() { proto.RegisterFile("Player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x6b, 0x32, 0x31,
	0x10, 0xc5, 0x71, 0x15, 0x71, 0x47, 0x3f, 0xd1, 0x7c, 0x3d, 0xec, 0xa5, 0x20, 0x7b, 0x2a, 0x3d,
	0xb4, 0x50, 0x3c, 0x15, 0x7a, 0x5a, 0x41, 0xa5, 0xdd, 0x2a, 0x55, 0xe9, 0x39, 0xae, 0xe3, 0x36,
	0xd6, 0x24, 0x92, 0x9d, 0x82, 0xfe, 0xf7, 0x65, 0x93, 0xa8, 0x3d, 0xec, 0x6d, 0x92, 0x79, 0xef,
	0x37, 0x33, 0x0f, 0x3a, 0xf3, 0x3d, 0x3f, 0xa1, 0x79, 0x38, 0x18, 0x4d, 0x9a, 0x35, 0xdd, 0x2b,
	0x8e, 0xa1, 0x9b, 0xb9, 0x32, 0xd1, 0x4a, 0x61, 0x46, 0xac, 0x07, 0xad, 0x64, 0x2f, 0x14, 0x92,
	0xd8, 0x44, 0xb5, 0x41, 0x70, 0xf7, 0xef, 0xaf, 0xc6, 0x20, 0x27, 0x6d, 0xbc, 0x06, 0x15, 0x4d,
	0xcf, 0x9a, 0x21, 0x40, 0xb6, 0x12, 0x29, 0x16, 0x05, 0xcf, 0x91, 0xf5, 0x21, 0x5c, 0x89, 0xb4,
	0xc8, 0xdf, 0xb9, 0x44, 0x2b, 0x08, 0xd9, 0x7f, 0x68, 0xf3, 0xef, 0xb4, 0xc8, 0xe7, 0xdc, 0x94,
	0x9f, 0xc1, 0xa0, 0xee, 0xc9, 0x63, 0x2e, 0xf1, 0x83, 0x67, 0xb8, 0x20, 0x6e, 0xa8, 0x82, 0x9c,
	0x5c, 0xa6, 0xcf, 0xd6, 0xbb, 0xa9, 0xda, 0x6a, 0x16, 0x42, 0xed, 0xe8, 0x9a, 0x65, 0x79, 0x8a,
	0x02, 0x5b, 0xb6, 0xa1, 0x2e, 0x26, 0x87, 0xa8, 0x6e, 0x1f, 0x5d, 0x68, 0x8a, 0x94, 0x1f, 0x27,
	0x87, 0xa8, 0x61, 0x21, 0xcf, 0xd0, 0xf6, 0x10, 0x4b, 0x00, 0x08, 0xce, 0xd7, 0xb1, 0x0e, 0x34,
	0x94, 0xdb, 0xa8, 0x5c, 0xb3, 0x0f, 0x21, 0x2a, 0x42, 0xb3, 0x14, 0x12, 0x2d, 0xab, 0x11, 0xdf,
	0x5e, 0xbd, 0x84, 0xd2, 0xa2, 0x09, 0xe5, 0x25, 0x9d, 0xc7, 0x4b, 0x7b, 0x69, 0x7e, 0x14, 0x63,
	0x00, 0x7a, 0xbd, 0x7b, 0xd3, 0xb9, 0xc8, 0xa6, 0xa3, 0xeb, 0x88, 0xed, 0x48, 0x18, 0x37, 0x22,
	0x1e, 0x42, 0xc7, 0x1b, 0x16, 0xc4, 0x09, 0x2b, 0x1d, 0x3d, 0x68, 0xe9, 0xf5, 0xce, 0xf6, 0xdd,
	0x79, 0xf1, 0x0b, 0xf4, 0xbd, 0x6b, 0x6c, 0xc4, 0x26, 0xf9, 0xe2, 0x2a, 0xaf, 0xb6, 0xda, 0x74,
	0x82, 0x6b, 0x3a, 0x36, 0x90, 0xf8, 0x1e, 0x6e, 0xb2, 0xa7, 0xc2, 0x45, 0x5b, 0x26, 0xfe, 0xa9,
	0xcd, 0x7e, 0x33, 0x7b, 0x2d, 0x09, 0xf2, 0xe4, 0x13, 0xf7, 0x84, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0a, 0x3d, 0xe0, 0x4c, 0x2a, 0x02, 0x00, 0x00,
}
