// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Player.proto

/*
Package Player is a generated protocol buffer package.

It is generated from these files:
	Player.proto

It has these top-level messages:
	CPlayerInfo
	CPlayerItem
*/
package Player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CPlayerInfo struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	EnterTime        *uint64 `protobuf:"varint,3,req,name=enterTime" json:"enterTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerInfo) Reset()                    { *m = CPlayerInfo{} }
func (m *CPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*CPlayerInfo) ProtoMessage()               {}
func (*CPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CPlayerInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CPlayerInfo) GetEnterTime() uint64 {
	if m != nil && m.EnterTime != nil {
		return *m.EnterTime
	}
	return 0
}

type CPlayerItem struct {
	Itemid           *uint32 `protobuf:"varint,1,req,name=itemid" json:"itemid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerItem) Reset()                    { *m = CPlayerItem{} }
func (m *CPlayerItem) String() string            { return proto.CompactTextString(m) }
func (*CPlayerItem) ProtoMessage()               {}
func (*CPlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CPlayerItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

func init() {
	proto.RegisterType((*CPlayerInfo)(nil), "Player.cPlayerInfo")
	proto.RegisterType((*CPlayerItem)(nil), "Player.cPlayerItem")
}

func init() { proto.RegisterFile("Player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x09, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xac, 0xb8, 0xb8,
	0x93, 0x21, 0x4c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x2e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05,
	0x26, 0x0d, 0x5e, 0x21, 0x1e, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x26, 0x0d,
	0x4e, 0x21, 0x41, 0x2e, 0xce, 0xd4, 0xbc, 0x92, 0xd4, 0xa2, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x66,
	0x05, 0x26, 0x0d, 0x16, 0x25, 0x59, 0x84, 0xde, 0x92, 0xd4, 0x5c, 0x21, 0x3e, 0x2e, 0xb6, 0xcc,
	0x92, 0xd4, 0x5c, 0x98, 0x7e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xa5, 0x25, 0x5e, 0x71,
	0x00, 0x00, 0x00,
}
