// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Player.proto

/*
Package Player is a generated protocol buffer package.

It is generated from these files:
	Player.proto

It has these top-level messages:
	CPlayerConnect
	CPlayerCreator
	CPlayerInfo
	CPlayerItem
	CPlayerTrun
*/
package Player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CPlayerConnect struct {
	Clinetid         *uint32 `protobuf:"varint,1,req,name=Clinetid" json:"Clinetid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerConnect) Reset()                    { *m = CPlayerConnect{} }
func (m *CPlayerConnect) String() string            { return proto.CompactTextString(m) }
func (*CPlayerConnect) ProtoMessage()               {}
func (*CPlayerConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CPlayerConnect) GetClinetid() uint32 {
	if m != nil && m.Clinetid != nil {
		return *m.Clinetid
	}
	return 0
}

type CPlayerCreator struct {
	ClientId         *uint32 `protobuf:"varint,1,req,name=ClientId" json:"ClientId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerCreator) Reset()                    { *m = CPlayerCreator{} }
func (m *CPlayerCreator) String() string            { return proto.CompactTextString(m) }
func (*CPlayerCreator) ProtoMessage()               {}
func (*CPlayerCreator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CPlayerCreator) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

type CPlayerInfo struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	EnterTime        *uint64 `protobuf:"varint,3,req,name=enterTime" json:"enterTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerInfo) Reset()                    { *m = CPlayerInfo{} }
func (m *CPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*CPlayerInfo) ProtoMessage()               {}
func (*CPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CPlayerInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CPlayerInfo) GetEnterTime() uint64 {
	if m != nil && m.EnterTime != nil {
		return *m.EnterTime
	}
	return 0
}

type CPlayerItem struct {
	Itemid           *uint32 `protobuf:"varint,1,req,name=itemid" json:"itemid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerItem) Reset()                    { *m = CPlayerItem{} }
func (m *CPlayerItem) String() string            { return proto.CompactTextString(m) }
func (*CPlayerItem) ProtoMessage()               {}
func (*CPlayerItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CPlayerItem) GetItemid() uint32 {
	if m != nil && m.Itemid != nil {
		return *m.Itemid
	}
	return 0
}

type CPlayerTrun struct {
	ObjLogicID       *uint32 `protobuf:"varint,1,req,name=objLogicID" json:"objLogicID,omitempty"`
	FDir             *string `protobuf:"bytes,2,req,name=fDir" json:"fDir,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPlayerTrun) Reset()                    { *m = CPlayerTrun{} }
func (m *CPlayerTrun) String() string            { return proto.CompactTextString(m) }
func (*CPlayerTrun) ProtoMessage()               {}
func (*CPlayerTrun) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CPlayerTrun) GetObjLogicID() uint32 {
	if m != nil && m.ObjLogicID != nil {
		return *m.ObjLogicID
	}
	return 0
}

func (m *CPlayerTrun) GetFDir() string {
	if m != nil && m.FDir != nil {
		return *m.FDir
	}
	return ""
}

func init() {
	proto.RegisterType((*CPlayerConnect)(nil), "Player.cPlayerConnect")
	proto.RegisterType((*CPlayerCreator)(nil), "Player.cPlayerCreator")
	proto.RegisterType((*CPlayerInfo)(nil), "Player.cPlayerInfo")
	proto.RegisterType((*CPlayerItem)(nil), "Player.cPlayerItem")
	proto.RegisterType((*CPlayerTrun)(nil), "Player.cPlayerTrun")
}

func init() { proto.RegisterFile("Player.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8d, 0x3f, 0xaf, 0x82, 0x50,
	0x0c, 0x47, 0xf3, 0xee, 0x23, 0xe4, 0xd1, 0x87, 0x44, 0x3b, 0xb1, 0x98, 0x10, 0x26, 0x26, 0xdd,
	0x5d, 0x61, 0x21, 0x71, 0x70, 0xe0, 0x0b, 0x20, 0x16, 0x73, 0x0d, 0xb7, 0xd7, 0x34, 0x75, 0xf0,
	0xdb, 0x3b, 0xf0, 0xcf, 0xad, 0xcd, 0xef, 0x9c, 0x1c, 0x88, 0x2f, 0x43, 0xfb, 0x26, 0x39, 0x3c,
	0xc5, 0xab, 0xc7, 0x70, 0xfc, 0xf2, 0x1c, 0x92, 0x6e, 0x3c, 0x4b, 0xcf, 0x4c, 0x9d, 0xe2, 0x16,
	0xfe, 0xca, 0xc1, 0x32, 0xa9, 0xbd, 0xa5, 0x3f, 0x99, 0x29, 0x36, 0xdf, 0x8c, 0x50, 0xab, 0x5e,
	0x26, 0x86, 0x58, 0xeb, 0x99, 0x39, 0xc1, 0xff, 0xc4, 0xd4, 0xdc, 0x7b, 0x04, 0x30, 0xb3, 0x8e,
	0x31, 0x04, 0xdc, 0x3a, 0x4a, 0x4d, 0x66, 0x8a, 0x08, 0x77, 0x10, 0x11, 0x2b, 0x49, 0x63, 0x1d,
	0xa5, 0xbf, 0x99, 0x29, 0x82, 0x7c, 0xbf, 0xba, 0x4a, 0x0e, 0x13, 0x08, 0xad, 0x92, 0x5b, 0xf2,
	0xc7, 0x65, 0x6e, 0xe4, 0xc5, 0x88, 0x00, 0xfe, 0xfa, 0x38, 0xfb, 0xbb, 0xed, 0xea, 0x6a, 0x4d,
	0xf4, 0x95, 0x95, 0x31, 0xf1, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xfb, 0x5a, 0x03, 0xea, 0x00,
	0x00, 0x00,
}
